<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;

class Brand extends Model
{
    protected $fillable = [
        'name', 'description',
        'entry_kit', 'logo',
        'id_string', 'company_id',
        'category_id', 'industry_category_id'
    ];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    public function delete()
    {
        File::delete($this->entry_kit);
        File::delete($this->logo);
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function industryCategory()
    {
        return $this->belongsTo('App\IndustryCategory');
    }

    public function users()
    {
        return $this->belongsToMany('App\User')->as('score')
            ->withPivot('intent', 'content', 'process', 'health', 'performance', 'total',
                'good', 'bad', 'improvement')->withTimestamps();
    }

    public function getEntryKitAttribute($value)
    {
        return 'uploads/' . $value;
    }

    public function getLogoAttribute($value)
    {
        return 'uploads/' . $value;
    }

}
