<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
        'name',
        'address',
        'ceo_name',
        'ceo_email',
        'ceo_contact_number',
        'user_id',
        'vat_registration_number',
    ];

    public function brands()
    {
        return $this->hasMany('App\Brand');
    }

    public function delete()
    {
        $brands = $this->brands;

        foreach ($brands as $b) {
            $b->delete();
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
