<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'designation', 'contact_number',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $attributes = [
        'role_id' => 4
    ];

    public function company()
    {
        return $this->hasOne('App\Company');
    }

    public function role()
    {
        return $this->belongsTo('App\Role');
    }

    public function blockedEntries()
    {
        return $this->hasMany('App\BlockedEntry');
    }

    public function brands()
    {
        return $this->belongsToMany('App\Brand')->as('score')
            ->withPivot('intent', 'content', 'process', 'health', 'performance', 'total',
            'good', 'bad', 'improvement')->withTimestamps();
    }

    public function industryCategories()
    {
        return $this->belongsToMany('App\IndustryCategory')->withTimestamps();
    }

    public function delete()
    {

        if($this->company) {
            $this->company->delete();
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
